# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c79736af4994c45a612f08c5b02cfc8e9b0f6682499a4087fe9567a256434c475a8fed00ce70903790347a9bf6868315cfb1244eb76fcc918ac542da3d9ad03

test:
  secret_key_base: 07400adefc3b6cb5fcc57b7eb2e404775b1a140471bc4080344c19ad873b56ba8e48f69571d0a850092170c56031efccd6344774506a4b9c81e526952454b711

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
